<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Question;
use Illuminate\Database\Seeder;

class FullSkd110QuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $catTWK = Category::where('code', 'TWK')->first();
        $catTIU = Category::where('code', 'TIU')->first();
        $catTKP = Category::where('code', 'TKP')->first();

        if (!$catTWK || !$catTIU || !$catTKP) {
            $this->command->error('Kategori TWK, TIU, TKP belum ditemukan.');
            return;
        }

        // Hapus soal lama agar rapi tepat 110 soal standar nasional
        Question::truncate();

        $data = [
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Pilar Negara (Pancasila)',
                'question' => 'Sidang pertama BPUPKI yang berlangsung pada tanggal 29 Mei - 1 Juni 1945 memiliki agenda utama untuk merumuskan...',
                'options' => ["Dasar negara Indonesia merdeka","Naskah proklamasi kemerdekaan","Struktur kabinet kementerian","Rancangan batang tubuh UUD","Garis perbatasan wilayah kedaulatan"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Sidang pertama BPUPKI fokus mendengarkan pidato gagasan dasar negara Indonesia merdeka oleh Moh. Yamin, Soepomo, dan Ir. Soekarno pada 1 Juni 1945.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Pilar Negara (Pancasila)',
                'question' => 'Seorang ASN menolak memberikan perlakuan istimewa kepada kerabat dekatnya dalam proses pengadaan barang dan jasa. Sikap tersebut mencerminkan pengamalan sila...',
                'options' => ["Ketuhanan Yang Maha Esa","Kemanusiaan yang adil dan beradab","Persatuan Indonesia","Kerakyatan yang dipimpin oleh hikmat kebijaksanaan","Keadilan sosial bagi seluruh rakyat Indonesia"],
                'correct_answer' => 4,
                'scores' => null,
                'explanation' => 'Sila ke-5 menuntut sikap adil, tidak diskriminatif, menolak nepotisme, dan memberikan perlakuan setara bagi semua warga negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Pilar Negara (Pancasila)',
                'question' => 'Pancasila dinyatakan sebagai ideologi terbuka bagi bangsa Indonesia. Makna sifat terbuka tersebut adalah...',
                'options' => ["Nilai-nilai dasarnya dapat diubah sewaktu-waktu sesuai keinginan penguasa","Mampu menyesuaikan diri dengan perkembangan zaman tanpa mengubah nilai-nilai dasarnya","Bebas menerima seluruh paham asing termasuk liberalisme ekstrem","Bisa ditafsirkan sebebas-bebasnya oleh setiap individu","Hanya berlaku bagi bangsa Indonesia pada era modern saja"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Ideologi terbuka berarti fleksibel dalam nilai instrumental dan praksis dalam merespons kemajuan zaman tanpa mengubah nilai dasarnya.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Pilar Negara (Pancasila)',
                'question' => 'Dalam musyawarah warga, seseorang bersikeras memaksakan gagasannya dan enggan menerima hasil mufakat bersama. Hal tersebut melanggar butir Pancasila sila...',
                'options' => ["Sila ke-1","Sila ke-2","Sila ke-3","Sila ke-4","Sila ke-5"],
                'correct_answer' => 3,
                'scores' => null,
                'explanation' => 'Sila ke-4 menegaskan butir larangan memaksakan kehendak serta kewajiban menghormati dan melaksanakan hasil musyawarah.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Pilar Negara (Pancasila)',
                'question' => 'Aksi solidaritas kemanusiaan berupa pengiriman bantuan medis dan logistik ke negara sahabat yang tertimpa musibah perang merupakan pengamalan sila...',
                'options' => ["Pertama","Kedua","Ketiga","Keempat","Kelima"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Sila ke-2 (Kemanusiaan yang adil dan beradab) menuntut kepedulian terhadap nilai-nilai kemanusiaan universal tanpa memandang batas wilayah.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Pilar Negara (Pancasila)',
                'question' => 'Konsekuensi yuridis Pancasila sebagai sumber dari segala sumber hukum negara Republik Indonesia adalah...',
                'options' => ["Seluruh materi peraturan perundang-undangan di Indonesia tidak boleh bertentangan dengan Pancasila","Pancasila dapat menggantikan Kitab Undang-Undang Hukum Pidana","Hakim bebas memutus tanpa dasar undang-undang","UUD 1945 berkedudukan lebih tinggi dari Pancasila","Presiden boleh menerbitkan peraturan tanpa batas kewenangan"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Pasal 2 UU No. 12 Tahun 2011 menegaskan Pancasila sebagai norma dasar (grundnorm) dan sumber segala sumber hukum negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Pilar Negara (Pancasila)',
                'question' => 'Rumusan Pancasila yang sah dan mengikat secara yuridis konstitusional bagi seluruh bangsa Indonesia tercantum dalam...',
                'options' => ["Piagam Jakarta 22 Juni 1945","Pidato 1 Juni 1945 Ir. Soekarno","Pembukaan UUD 1945 alinea keempat","Dekrit Presiden 5 Juli 1959","Ketetapan MPRS No. XX/MPRS/1966"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Rumusan sah dan resmi Pancasila berada di Pembukaan UUD NRI 1945 alinea IV yang disahkan PPKI pada 18 Agustus 1945.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Menurut Pasal 1 ayat (2) UUD 1945 hasil amandemen, kedaulatan berada di tangan rakyat dan dilaksanakan...',
                'options' => ["Sepenuhnya oleh Majelis Permusyawaratan Rakyat","Menurut Undang-Undang Dasar","Oleh Presiden selaku kepala negara","Melalui pemilu legislatif semata","Berdasarkan putusan Mahkamah Konstitusi"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Amandemen ketiga mengubah bunyi Pasal 1 ayat (2) menjadi: "Kedaulatan berada di tangan rakyat dan dilaksanakan menurut Undang-Undang Dasar."',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Pemberhentian Presiden dan/atau Wakil Presiden dalam masa jabatannya menurut Pasal 7A UUD 1945 harus diusulkan oleh...',
                'options' => ["DPR kepada MPR setelah diputus oleh Mahkamah Konstitusi","Mahkamah Agung kepada MPR secara langsung","Dewan Perwakilan Daerah bersama Komisi Yudisial","Kejaksaan Agung bersama Mahkamah Konstitusi","Kepolisian Negara Republik Indonesia"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'DPR mengajukan dugaan pelanggaran hukum ke MK. Jika MK membenarkan, DPR meneruskan usul pemberhentian kepada MPR.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Kewenangan menguji undang-undang terhadap Undang-Undang Dasar (judicial review) berada pada ranah kewenangan lembaga...',
                'options' => ["Mahkamah Agung","Mahkamah Konstitusi","Komisi Yudisial","Dewan Perwakilan Rakyat","Badan Pemeriksa Keuangan"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Pasal 24C ayat (1) UUD 1945 mengatur MK berwenang menguji undang-undang terhadap UUD 1945.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Kewajiban negara memprioritaskan alokasi anggaran pendidikan sekurang-kurangnya 20% dari APBN dan APBD diatur dalam Pasal...',
                'options' => ["Pasal 27","Pasal 28","Pasal 30","Pasal 31","Pasal 33"],
                'correct_answer' => 3,
                'scores' => null,
                'explanation' => 'Pasal 31 ayat (4) UUD 1945 mewajibkan alokasi anggaran pendidikan minimal 20% dari APBN dan APBD untuk mencerdaskan kehidupan bangsa.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Ciri pokok sistem pemerintahan presidensial di Indonesia berdasarkan UUD 1945 adalah...',
                'options' => ["Presiden bertanggung jawab langsung kepada parlemen DPR","Menteri-menteri diangkat dan bertanggung jawab kepada Presiden","Perdana menteri memimpin jalannya rapat kabinet","Presiden dapat membubarkan parlemen secara sepihak","Parlemen berwenang menjatuhkan mosi tidak percaya"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Pasal 17 UUD 1945 menegaskan menteri diangkat dan diberhentikan oleh Presiden serta bertanggung jawab kepada Presiden.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Berdasarkan Pasal 22D UUD 1945, Dewan Perwakilan Daerah (DPD) berhak mengajukan RUU kepada DPR terkait bidang...',
                'options' => ["Pertahanan dan persenjataan militer","Otonomi daerah, hubungan pusat dan daerah, serta pengelolaan SDA","Hukum pidana dan tata peradilan","Gelar dan tanda jasa kenegaraan","Perjanjian ekstradisi internasional"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Pasal 22D membatasi hak inisiatif RUU oleh DPD pada aspek otonomi daerah, hubungan pusat-daerah, pemekaran wilayah, dan perimbangan keuangan.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Pokok pikiran pertama Pembukaan UUD 1945 menegaskan bahwa negara...',
                'options' => ["Melindungi segenap bangsa dan seluruh tumpah darah dengan berdasar atas persatuan","Hendak mewujudkan keadilan sosial bagi seluruh rakyat","Berkedaulatan rakyat berdasar permusyawaratan","Berdasar atas Ketuhanan Yang Maha Esa","Mengutamakan kepentingan golongan tertentu"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Pokok pikiran pertama Pembukaan UUD 1945 adalah persatuan: Negara melindungi segenap bangsa Indonesia dan seluruh tumpah darah Indonesia.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'UUD 1945 & Konstitusi',
                'question' => 'Bab Hak Asasi Manusia (Pasal 28A s/d 28J) secara komprehensif dimasukkan ke dalam UUD 1945 pada amandemen...',
                'options' => ["Pertama (1999)","Kedua (2000)","Ketiga (2001)","Keempat (2002)","Dekrit 1959"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Bab XA Hak Asasi Manusia (Pasal 28A - 28J) disahkan pada Perubahan Kedua UUD 1945 tahun 2000.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bhinneka Tunggal Ika',
                'question' => 'Semboyan Bhinneka Tunggal Ika dipetik dari karya sastra Kakawin Sutasoma yang ditulis pada era kerajaan...',
                'options' => ["Singasari","Sriwijaya","Majapahit","Mataram Kuno","Tarumanegara"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Kakawin Sutasoma digubah oleh Mpu Tantular pada masa pemerintahan Raja Hayam Wuruk di Kerajaan Majapahit abad ke-14.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bhinneka Tunggal Ika',
                'question' => 'Kecenderungan memandang budaya kelompok sendiri paling unggul dan merendahkan tradisi suku lain disebut...',
                'options' => ["Primordialisme","Etnosentrisme","Chauvinisme","Xenosentrisme","Asimilasi"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Etnosentrisme adalah sikap memandang budaya sendiri sebagai pusat tolok ukur dan meremehkan budaya lain.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bhinneka Tunggal Ika',
                'question' => 'Langkah pimpinan instansi pemerintah yang paling mencerminkan prinsip Bhinneka Tunggal Ika dalam penugasan kerja adalah...',
                'options' => ["Mengelompokkan pegawai berdasarkan kesamaan suku agar kompak","Membentuk tim kerja lintas latar belakang suku dan agama secara adil","Melarang penggunaan busana daerah di acara resmi kantor","Hanya memberikan promosi kepada putra daerah saja","Menolak pegawai mutasi dari luar pulau"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Membentuk tim lintas suku dan agama menumbuhkan kolaborasi inklusif dan memupuk toleransi nyata dalam birokrasi.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bhinneka Tunggal Ika',
                'question' => 'Faktor pendorong historis terkuat yang menyatukan beragam suku bangsa di nusantara menjadi satu bangsa adalah...',
                'options' => ["Perasaan senasib dan seperjuangan akibat penindasan kolonialisme","Kemiripan iklim tropis di seluruh kepulauan","Dominasi militer salah satu kerajaan besar","Keseragaman garis keturunan nenek moyang","Pemusatan pusat industri di ibu kota"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Rasa senasib sepenanggungan dijajah bangsa asing menumbuhkan tekad kuat bersatu mendirikan negara merdeka.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bhinneka Tunggal Ika',
                'question' => 'Sikap toleransi antarumat beragama yang selaras dengan nilai konstitusi Indonesia adalah...',
                'options' => ["Mengikuti peribadatan ritual agama lain demi solidaritas sosial","Memberi kebebasan dan jaminan rasa aman bagi umat lain beribadah","Menyatukan pokok ajaran semua agama menjadi satu aliran","Membatasi rumah ibadah hanya bagi kalangan mayoritas","Menghilangkan perayaan hari besar keagamaan"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Toleransi hakiki menghormati hak beribadah setiap insan dengan damai tanpa kompromi akidah masing-masing.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Nasionalisme & Bela Negara',
                'question' => 'Deklarasi Djuanda 13 Desember 1957 merupakan tonggak kedaulatan maritim Indonesia karena...',
                'options' => ["Mengubah perairan antarpulau menjadi wilayah kedaulatan teritorial utuh NKRI","Membatalkan seluruh kesepakatan KMB secara sepihak","Menetapkan zona ekonomi eksklusif 200 mil laut","Mengambil alih seluruh pelabuhan milik Belanda","Membentuk angkatan laut terkuat di Asia Tenggara"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Deklarasi Djuanda menyatukan perairan pedalaman nusantara menjadi bagian mutlak wilayah kedaulatan kepulauan Indonesia.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Nasionalisme & Bela Negara',
                'question' => 'Menurut UU No. 23 Tahun 2019, Komponen Cadangan (Komcad) bertugas untuk...',
                'options' => ["Menggantikan tentara reguler di masa damai","Memperbesar kekuatan Komponen Utama (TNI) saat keadaan darurat militer/perang","Mengatur ketertiban lalu lintas jalan raya","Menjadi satuan pengamanan instansi swasta","Mengawasi perbatasan tanpa komando TNI"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Komcad dipersiapkan melalui pelatihan dasar militer untuk sewaktu-waktu dikerahkan memperkuat Komponen Utama TNI.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Nasionalisme & Bela Negara',
                'question' => 'Tindakan kaum muda membawa Soekarno-Hatta ke Rengasdengklok pada 16 Agustus 1945 bertujuan untuk...',
                'options' => ["Menjauhkan Soekarno-Hatta dari pengaruh dan janji kemerdekaan pihak Jepang","Menyerahkan kekuasaan kepada komandan sekutu","Menyusun naskah proklamasi di markas tentara Dai Nippon","Mencegah kedatangan armada militer Belanda di Tanjung Priok","Menyandera para perwira tinggi militer Jepang"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Pemuda mendesak kemerdekaan diproklamasikan segera tanpa campur tangan dan janji manis penguasa militer Jepang.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Nasionalisme & Bela Negara',
                'question' => 'Perang siber yang membobol data strategis kementerian dan melumpuhkan layanan publik dikategorikan sebagai ancaman...',
                'options' => ["Militer konvensional","Nirmiliter (non-militer)","Agresi militer fisik","Spionase darat konvensional","Sabotase pangkalan laut"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Ancaman nirmiliter memanfaatkan teknologi digital, informasi, dan jaringan untuk menggoyahkan stabilitas dan keamanan negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Nasionalisme & Bela Negara',
                'question' => 'Wujud nyata pengabdian bela negara bagi seorang ASN dalam kehidupan sehari-hari adalah...',
                'options' => ["Membeli persenjataan tempur secara swadaya","Memberikan pelayanan publik profesional, berintegritas, dan bersih dari KKN","Membawa senjata dinas saat berada di ruang pelayanan","Membuat perdebatan politik di grup media sosial","Menolak penugasan di daerah pedalaman"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Bela negara profesi bagi ASN adalah dedikasi memberikan pelayanan prima tanpa korupsi demi kemajuan bangsa.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bahasa Indonesia Baku',
                'question' => 'Kalimat di bawah ini yang merupakan contoh kalimat efektif adalah...',
                'options' => ["Bagi para peserta ujian diharapkan hadir tepat pada waktunya.","Meskipun hujan lebat, namun apel pagi tetap berjalan khidmat.","Pemerintah daerah mengalokasikan anggaran khusus penanganan kemiskinan ekstrem.","Dalam rapat kemarin membahas tentang kenaikan tunjangan kinerja.","Para guru-guru diimbau agar supaya rajin membaca buku modul."],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Opsi C memiliki struktur S-P-O yang lengkap dan lugas tanpa pemborosan kata atau tumpang tindih konjungsi.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bahasa Indonesia Baku',
                'question' => 'Deretan kata serapan yang seluruhnya baku sesuai kaidah EYD Edisi V adalah...',
                'options' => ["Kwalitas, metoda, analisa","Kualitas, metode, analisis","Kualitet, methode, analisa","Kwalitas, metodhe, analyse","Kualitet, metode, analisir"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Kaidah penyerapan baku: quality -> kualitas, method -> metode, analysis -> analisis.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bahasa Indonesia Baku',
                'question' => 'Penggunaan tanda baca titik dua (:) yang tepat menurut EYD terdapat pada kalimat...',
                'options' => ["Ibu membeli sayur-mayur seperti: bayam, sawi, dan kangkung.","Peralatan kantor yang dibeli meliputi: kertas, tinta, dan map.","Panitia memerlukan perlengkapan pentas: mikrofon, lampu sorot, dan proyektor.","Faktor penentu kelulusan ujian adalah: ketekunan dan doa.","Peserta wajib membawa: kartu ujian dan pensil 2B."],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Titik dua digunakan setelah pernyataan lengkap yang diikuti rincian pemerian.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bahasa Indonesia Baku',
                'question' => 'Gagasan pokok sebuah paragraf argumentasi biasanya terletak pada...',
                'options' => ["Kalimat utama paragraf","Seluruh kalimat penjelas","Kata hubung antarkalimat","Catatan kaki paragraf","Rincian angka statistik"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Gagasan pokok atau ide utama tertuang secara eksplisit atau implisit pada kalimat utama paragraf.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTWK->id,
                'sub_category' => 'Bahasa Indonesia Baku',
                'question' => 'Penulisan gelar akademik yang benar menurut kaidah ejaan resmi adalah...',
                'options' => ["Budi Santoso S.E., M.M.","Budi Santoso, S.E., M.M.","Budi Santoso, SE, MM","Budi Santoso, S,E., M,M.","Budi Santoso S.E M.M."],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Antara nama dan gelar dipisahkan tanda koma, dan tiap singkatan gelar diakhiri tanda titik (S.E., M.M.).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Verbal (Analogi)',
                'question' => 'MOBIL : BENSIN = MANUSIA : ...',
                'options' => ["Pakaian","Makanan","Rumah","Udara","Pikiran"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Mobil membutuhkan bensin sebagai sumber energi untuk bergerak, sebagaimana manusia membutuhkan makanan sebagai energi beraktivitas.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Verbal (Analogi)',
                'question' => 'APOTEKER : OBAT = KOKI : ...',
                'options' => ["Restoran","Pisau","Masakan","Dapur","Bumbu"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Apoteker menghasilkan atau meracik obat, sedangkan koki memasak dan menghasilkan masakan.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Verbal (Analogi)',
                'question' => 'DINGIN : BEKU = PANAS : ...',
                'options' => ["Hangat","Cair","Mendidih","Uap","Api"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Tingkatan intensitas tinggi dari dingin adalah beku, sedangkan tingkatan intensitas sangat tinggi dari panas adalah mendidih.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Verbal (Analogi)',
                'question' => 'PIKIRAN : OTAK = PERASAAN : ...',
                'options' => ["Tubuh","Hati","Jiwa","Mata","Darah"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Pikiran diasosiasikan berpusat pada otak, sedangkan perasaan diasosiasikan berpusat pada hati.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Verbal (Analogi)',
                'question' => 'MIKROSKOP : BAKTERI = TELESKOP : ...',
                'options' => ["Matahari","Bintang","Lensa","Laboratorium","Mata"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Mikroskop digunakan untuk melihat objek mikro seperti bakteri, sedangkan teleskop untuk mengamati benda langit seperti bintang.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Verbal (Analogi)',
                'question' => 'KERTAS : BUKU = BATA : ...',
                'options' => ["Semen","Pasir","Dinding","Tanah","Pondasi"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Lembaran kertas disusun membentuk buku, susunan bata membentuk dinding.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Verbal (Analogi)',
                'question' => 'HAUS : MINUM = LAPAR : ...',
                'options' => ["Kenyang","Makan","Nasi","Dahaga","Piring"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Kondisi haus diatasi dengan minum, kondisi lapar diatasi dengan makan.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Logika Silogisme',
                'question' => 'Semua dosen berpendidikan magister. Sebagian dosen adalah peneliti jurnal internasional. Kesimpulan yang sah adalah...',
                'options' => ["Semua peneliti jurnal internasional adalah dosen","Sebagian peneliti jurnal internasional berpendidikan magister","Tidak ada dosen yang menjadi peneliti jurnal","Semua dosen adalah peneliti jurnal internasional","Semua yang berpendidikan magister adalah dosen"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Karena sebagian dosen adalah peneliti, dan seluruh dosen berpendidikan magister, maka sebagian peneliti tersebut berpendidikan magister.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Logika Silogisme',
                'question' => 'Jika hari hujan deras, maka jalan protokol tergenang air. Hari ini jalan protokol tidak tergenang air. Kesimpulan yang sah adalah...',
                'options' => ["Hari hujan rintik-rintik","Hari ini tidak hujan deras","Jalan protokol ditutup polisi","Saluran air berfungsi dengan baik","Kemarin tidak turun hujan"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Berdasarkan kaidah Modus Tollens (p -> q, ~q, maka ~p): Jika p (hujan deras) maka q (tergenang). Karena ~q (tidak tergenang), maka ~p (tidak hujan deras).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Logika Silogisme',
                'question' => 'Semua peserta yang lulus passing grade berhak mengikuti SKB. Sebagian peserta dari instansi X lulus passing grade. Kesimpulan yang sah adalah...',
                'options' => ["Semua peserta instansi X berhak mengikuti SKB","Sebagian peserta instansi X berhak mengikuti SKB","Tidak ada peserta instansi X yang ikut SKB","Semua yang ikut SKB berasal dari instansi X","Peserta yang tidak lulus SKB bukan dari instansi X"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Premis partikular menghasilkan kesimpulan partikular: Sebagian peserta instansi X yang lulus PG berhak ikut SKB.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Logika Silogisme',
                'question' => 'Semua mamalia menyusui anaknya. Ikan paus adalah mamalia laut. Kesimpulan yang benar adalah...',
                'options' => ["Ikan paus bertelur di laut","Ikan paus menyusui anaknya","Semua hewan laut menyusui anaknya","Ikan paus bernapas dengan insang","Sebagian ikan paus bukan mamalia"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Silogisme kategorik standar: Semua M adalah P, S adalah M, maka S adalah P (Ikan paus menyusui anaknya).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Logika Silogisme',
                'question' => 'Tidak ada koruptor yang bermoral luhur. Sebagian oknum pejabat melakukan korupsi. Kesimpulan yang tepat adalah...',
                'options' => ["Semua oknum pejabat bermoral luhur","Sebagian oknum pejabat tidak bermoral luhur","Semua yang bermoral luhur adalah oknum pejabat","Korupsi diperbolehkan bagi oknum pejabat","Tidak ada oknum pejabat yang korupsi"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Karena ada oknum pejabat yang menjadi koruptor, dan tak ada koruptor bermoral luhur, maka sebagian oknum pejabat tersebut tidak bermoral luhur.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Logika Silogisme',
                'question' => 'Jika seorang pegawai disiplin, maka ia datang tepat waktu. Jika pegawai datang tepat waktu, maka pekerjaan selesai teratur. Budi adalah pegawai yang disiplin. Kesimpulan yang sah adalah...',
                'options' => ["Budi sering terlambat datang","Pekerjaan Budi selesai secara teratur","Budi tidak menyukai pekerjaan kantor","Hanya Budi yang datang tepat waktu","Budi mendapat kenaikan pangkat segera"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Silogisme hipotetis rantai: Disiplin -> Tepat Waktu -> Kerja Teratur. Karena Budi disiplin, maka pekerjaannya selesai teratur.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Penalaran Analitis',
                'question' => 'Lima siswa A, B, C, D, dan E mengikuti tes. Nilai A lebih tinggi dari B. Nilai C lebih tinggi dari A. Nilai D lebih rendah dari B namun lebih tinggi dari E. Siapakah siswa yang memperoleh nilai tertinggi?',
                'options' => ["A","B","C","D","E"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Urutan peringkat nilai: C > A > B > D > E. Maka peraih nilai tertinggi adalah C.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Penalaran Analitis',
                'question' => 'Dalam antrean tiket kereta: P berada di depan Q. R berada di belakang Q. S berada di antara P dan Q. Siapakah yang berdiri pada urutan paling depan?',
                'options' => ["P","Q","R","S","Tidak dapat ditentukan"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Urutan dari depan ke belakang: P -> S -> Q -> R. Maka yang paling depan adalah P.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Penalaran Analitis',
                'question' => 'Enam orang duduk berjejer di bioskop. Andi duduk di sebelah kiri Budi. Cici duduk di antara Budi dan Deni. Eko duduk di ujung paling kanan. Farhan di sebelah kiri Andi. Siapakah yang duduk di ujung paling kiri?',
                'options' => ["Andi","Farhan","Budi","Cici","Deni"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Dari informasi: Farhan berada di sebelah kiri Andi, dan Andi di sebelah kiri Budi. Maka urutan paling kiri adalah Farhan.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Penalaran Analitis',
                'question' => 'Jadwal dinas 4 dokter: Dokter W tidak berdinas pada hari Senin. Dokter X selalu berdinas sehari setelah dokter W. Dokter Y berdinas dua hari sebelum dokter Z. Jika dokter Z berdinas hari Kamis, hari apakah dokter W berdinas?',
                'options' => ["Selasa","Rabu","Kamis","Jumat","Sabtu"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Dokter Z hari Kamis, Y dua hari sebelumnya (Selasa). Sisa slot hari Senin dan Rabu/Jumat. Karena W tidak Senin dan X sesudahnya, jika W Selasa maka bentrok. Maka W berdinas Selasa dan X Rabu.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Penalaran Analitis',
                'question' => 'Tinggi badan Rahma lebih dari Sinta. Sinta lebih tinggi dari Tina. Umar lebih tinggi dari Rahma. Siapakah yang tinggi badannya berada pada urutan kedua dari atas?',
                'options' => ["Umar","Rahma","Sinta","Tina","Sinta dan Tina"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Urutan tinggi badan dari paling tinggi: Umar > Rahma > Sinta > Tina. Urutan kedua tertinggi adalah Rahma.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Numerik',
                'question' => 'Berapakah nilai dari (0,75 × 2/3) + (1/4 ÷ 0,5)?',
                'options' => ["0,75","1,00","1,25","1,50","2,00"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => '(3/4 × 2/3) = 2/4 = 0,5. (1/4 ÷ 1/2) = 1/4 × 2/1 = 2/4 = 0,5. Jadi 0,5 + 0,5 = 1,00.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Numerik',
                'question' => 'Jika a = 3 dan b = -2, maka nilai dari 2a² - 3ab + b³ adalah...',
                'options' => ["28","24","18","14","12"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => '2(3²) - 3(3)(-2) + (-2)³ = 2(9) - (-18) + (-8) = 18 + 18 - 8 = 28.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Numerik',
                'question' => 'Jika x = 16% dari 250 dan y = 25% dari 160, maka hubungan yang benar antara x dan y adalah...',
                'options' => ["x > y","x < y","x = y","x = 2y","Hubungan x dan y tidak dapat ditentukan"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'x = 0,16 × 250 = 40. y = 0,25 × 160 = 40. Maka x = y (kaidah: a% dari b = b% dari a).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Numerik',
                'question' => 'Hasil perhitungan dari √144 + √625 - √441 adalah...',
                'options' => ["14","16","18","20","22"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => '√144 = 12, √625 = 25, √441 = 21. Maka 12 + 25 - 21 = 16.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Numerik',
                'question' => 'Berapakah 35% dari 4.000 dikurangi 20% dari 3.500?',
                'options' => ["600","700","800","900","1.000"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => '35% × 4.000 = 1.400. 20% × 3.500 = 700. Selisihnya = 1.400 - 700 = 700.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Deret Angka & Huruf',
                'question' => 'Tentukan suku berikutnya dari barisan angka: 3, 6, 12, 24, 48, ...',
                'options' => ["72","84","96","108","120"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Pola deret geometri dikalikan 2: 48 × 2 = 96.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Deret Angka & Huruf',
                'question' => 'Angka lanjutan dari pola deret: 2, 5, 10, 17, 26, ... adalah...',
                'options' => ["35","37","39","41","43"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Pola selisih bertingkat: +3, +5, +7, +9, maka berikutnya +11. 26 + 11 = 37 (atau n² + 1).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Deret Angka & Huruf',
                'question' => 'Tentukan suku berikutnya dari deret: 100, 95, 85, 70, 50, ...',
                'options' => ["25","30","35","40","45"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Pola pengurangan bertingkat: -5, -10, -15, -20, berikutnya -25. 50 - 25 = 25.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Deret Angka & Huruf',
                'question' => 'Tentukan angka berikutnya dari barisan Fibonacci: 1, 1, 2, 3, 5, 8, 13, ...',
                'options' => ["18","20","21","24","26"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Aturan Fibonacci: suku berikutnya adalah jumlah dua suku sebelumnya (8 + 13 = 21).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Deret Angka & Huruf',
                'question' => 'Lanjutan dari deret huruf berikut: B, D, G, K, ... adalah...',
                'options' => ["N","O","P","Q","R"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Konversi urutan alfabet: B(2) (+2) -> D(4) (+3) -> G(7) (+4) -> K(11) (+5) -> P(16).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Perbandingan & Cerita',
                'question' => 'Sebuah proyek renovasi gedung direncanakan selesai dalam 30 hari oleh 12 orang pekerja. Jika proyek ingin dipercepat selesai dalam 20 hari, berapa pekerja tambahan yang harus ditambahkan?',
                'options' => ["4 orang","6 orang","8 orang","10 orang","18 orang"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Perbandingan berbalik nilai: Beban kerja = 30 × 12 = 360 orang-hari. Untuk 20 hari: 360 ÷ 20 = 18 pekerja. Tambahan = 18 - 12 = 6 orang.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Perbandingan & Cerita',
                'question' => 'Jarak kota A ke kota B adalah 180 km. Mobil P berangkat dari A menuju B dengan kecepatan 60 km/jam, dan mobil Q berangkat dari B menuju A pada saat bersamaan dengan kecepatan 40 km/jam. Mereka akan berpapasan setelah menempuh perjalanan selama...',
                'options' => ["1 jam 30 menit","1 jam 48 menit","2 jam 00 menit","2 jam 15 menit","2 jam 30 menit"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Waktu berpapasan = Jarak ÷ (V1 + V2) = 180 ÷ (60 + 40) = 180 ÷ 100 = 1,8 jam. 0,8 jam × 60 menit = 48 menit. Jadi 1 jam 48 menit.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Perbandingan & Cerita',
                'question' => 'Seorang pedagang membeli sepeda seharga Rp 1.200.000. Setelah diperbaiki dengan biaya Rp 300.000, sepeda tersebut dijual dan memperoleh laba 20%. Harga jual sepeda tersebut adalah...',
                'options' => ["Rp 1.650.000","Rp 1.700.000","Rp 1.800.000","Rp 1.950.000","Rp 2.000.000"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Modal total = 1.200.000 + 300.000 = 1.500.000. Laba 20% = 0,20 × 1.500.000 = 300.000. Harga jual = 1.500.000 + 300.000 = Rp 1.800.000.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Perbandingan & Cerita',
                'question' => 'Sebuah jaket di toko busana diberi diskon berturut-turut 20% kemudian mendapat potongan tambahan 10%. Berapakah persentase diskon total sebenarnya?',
                'options' => ["30%","28%","26%","25%","22%"],
                'correct_answer' => 1,
                'scores' => null,
                'explanation' => 'Harga awal 100%. Setelah diskon 20% jadi 80%. Diskon lagi 10% dari 80% = 8%. Harga akhir 72%. Diskon total sesungguhnya = 100% - 72% = 28%.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Figural',
                'question' => 'Pada pola serial gambar, sebuah segitiga hitam berputar searah jarum jam sejauh 90° pada setiap langkah. Jika posisi awal menghadap ke atas, maka pada langkah ke-4 segitiga akan menghadap ke arah...',
                'options' => ["Atas","Kanan","Bawah","Kiri","Pojok kanan atas"],
                'correct_answer' => 3,
                'scores' => null,
                'explanation' => 'Awal (Atas) -> Langkah 1 (Kanan) -> Langkah 2 (Bawah) -> Langkah 3 (Kiri) -> Langkah 4 (Atas) / posisi sudut kembali ke atas setelah 4 rotasi penuh.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Figural',
                'question' => 'Manakah di antara bangun berikut yang memiliki sumbu simetri lipat paling banyak?',
                'options' => ["Persegi panjang","Segitiga sama sisi","Persegi","Belah ketupat","Trapesium sama kaki"],
                'correct_answer' => 2,
                'scores' => null,
                'explanation' => 'Persegi memiliki 4 sumbu simetri lipat (2 diagonal dan 2 tegak lurus sisi), lebih banyak dari segitiga sama sisi (3) dan persegi panjang (2).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTIU->id,
                'sub_category' => 'Kemampuan Figural',
                'question' => 'Suatu pola bangun geometri bertambah jumlah sisinya secara teratur: segitiga (3), segiempat (4), segilima (5). Bangun berikutnya pada deret tersebut adalah...',
                'options' => ["Segienam (heksagon)","Segitujuh (heptagon)","Lingkaran","Jajar genjang","Trapesium"],
                'correct_answer' => 0,
                'scores' => null,
                'explanation' => 'Pola penambahan sisi n + 1: setelah segilima (5 sisi) adalah segienam (6 sisi / heksagon).',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Saat Anda sedang bertugas di loket pelayanan perizinan pada jam sibuk, seorang warga lansia datang tampak bingung dan tidak mengerti cara mengisi formulir online di gawainya. Tindakan Anda adalah...',
                'options' => ["Menuntun dan membantu warga lansia tersebut secara ramah hingga permohonan selesai","Meminta satpam kantor mengarahkan warga tersebut ke meja informasi","Memberikan selebaran panduan dan memintanya membaca sendiri di ruang tunggu","Menolak berkasnya dan menyuruhnya mengajak anaknya datang besok","Menyuruhnya antre ulang karena memperlambat antrean pemohon di belakang"],
                'correct_answer' => 0,
                'scores' => [5,4,3,2,1],
                'explanation' => 'Pelayanan prima menomorsatukan empati dan bantuan proaktif terhadap kelompok rentan/lansia tanpa mengabaikan ketertiban loket.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Sistem komputer kantor pelayanan Anda mendadak mengalami gangguan jaringan internet, sementara antrean warga sudah menumpuk di ruang tunggu. Sikap terbaik Anda adalah...',
                'options' => ["Menjelaskan situasi dengan tenang, meminta maaf atas kendala, dan mencatat permohonan secara manual sementara sistem diperbaiki","Menutup loket dan meminta warga pulang serta kembali esok hari","Mendiamkan warga dan bermain gawai sambil menunggu jaringan normal","Menyalahkan bagian tim IT kantor di depan warga yang sedang antre","Meninggalkan ruangan pelayanan tanpa memberikan pemberitahuan apa pun"],
                'correct_answer' => 0,
                'scores' => [5,2,1,2,1],
                'explanation' => 'Komunikasi transparan, sikap tenang, permohonan maaf, dan inisiatif solusi cadangan (manual) mencerminkan tanggung jawab ASN.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Waktu operasional loket kantor pelayanan tinggal 5 menit lagi dan Anda bersiap pulang. Tiba-tiba seorang warga dari desa terpencil yang menempuh perjalanan 3 jam datang tergesa-gesa memohon pengurusan dokumen mendesak. Sikap Anda...',
                'options' => ["Melayani warga tersebut dengan tuntas dan ramah meskipun harus mengorbankan waktu pulang beberapa menit","Menolak dengan tegas karena jam kerja sudah hampir berakhir sesuai aturan","Meminta uang lembur khusus jika ingin dilayani di luar jam operasional","Menyuruhnya datang kembali esok pagi tanpa mendengarkan penjelasannya","Menyerahkan urusan tersebut kepada petugas kebersihan kantor"],
                'correct_answer' => 0,
                'scores' => [5,3,1,2,1],
                'explanation' => 'Orientasi pelayanan publik menuntut kepekaan dan kerelaan melayani masyarakat yang membutuhkan bantuan darurat.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Seorang warga melontarkan kritik pedas bernada emosional di media sosial terkait lambatnya proses verifikasi berkas di unit kerja Anda. Sikap Anda sebagai pengelola layanan adalah...',
                'options' => ["Merespons dengan santun, menyampaikan permohonan maaf, menanyakan nomor berkas untuk segera dicek, dan menjadikannya bahan evaluasi unit","Membalas komentar dengan nada emosional membela diri bahwa staf sudah bekerja keras","Menghapus komentar warga tersebut dan memblokir akunnya","Mengabaikan komentar karena menganggap warganet hanya mencari sensasi","Melaporkan akun warga tersebut ke kepolisian atas dugaan pencemaran nama baik"],
                'correct_answer' => 0,
                'scores' => [5,2,1,2,1],
                'explanation' => 'Kritik publik harus direspons dengan kepala dingin, profesional, komunikatif, dan dijadikan instrumen perbaikan mutu layanan.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda melihat rekan kerja Anda di loket sebelah melayani seorang warga dengan nada ketus dan kurang bersahabat. Yang Anda lakukan adalah...',
                'options' => ["Mengingatkannya dengan cara yang baik saat istirahat dan mencontohkan pelayanan yang ramah","Menegur rekan tersebut secara kasar di depan warga yang sedang dilayani","Membiarkan saja karena merasa bukan urusan pribadi Anda","Melaporkannya langsung ke pimpinan kantor agar dikenai sanksi berat","Ikut bersikap ketus kepada warga lain agar seragam"],
                'correct_answer' => 0,
                'scores' => [5,2,2,3,1],
                'explanation' => 'Mengingatkan rekan sejawat secara konstruktif dan empatik tanpa mempermalukannya di depan publik adalah tindakan bijak.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Seorang warga menawarkan uang terima kasih (amplop) di luar tarif resmi atas kecepatan Anda menyelesaikan permohonan izin usahanya. Sikap Anda...',
                'options' => ["Menolak uang tersebut dengan santun dan menjelaskan bahwa pelayanan prima adalah kewajiban tugas Anda tanpa biaya tambahan","Menerimanya karena merasa telah bekerja keras melayani dengan cepat","Menerimanya lalu mentraktir rekan-rekan staf satu ruangan","Meminta warga menyumbangkan uang tersebut ke kotak kas pribadi kantor","Menerima dengan syarat tidak boleh diceritakan kepada siapa pun"],
                'correct_answer' => 0,
                'scores' => [5,1,2,2,1],
                'explanation' => 'Integritas melarang menerima gratifikasi dalam bentuk apa pun terkait jabatan dan pelayanan publik.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Kantor Anda menerapkan standar baru alur pelayanan satu pintu (PTSP). Sebagai staf pelaksana, sikap Anda adalah...',
                'options' => ["Mempelajari SOP baru secara seksama dan aktif memberikan masukan perbaikan jika ada kendala di lapangan","Mengeluh karena merasa SOP baru membuat pekerjaan lebih rumit","Tetap menjalankan kebiasaan lama tanpa menghiraukan SOP baru","Menunggu teguran atasan baru mau mempelajari alur baru","Meminta pindah unit kerja yang beban kerjanya lebih santai"],
                'correct_answer' => 0,
                'scores' => [5,2,1,2,1],
                'explanation' => 'Kepatuhan pada inovasi tata kelola dan proaktif menyukseskan program instansi merupakan cerminan ASN profesional.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Terdapat seorang penyandang disabilitas tunarungu yang membutuhkan informasi di kantor Anda, namun kantor belum memiliki penerjemah bahasa isyarat. Yang Anda lakukan adalah...',
                'options' => ["Mengajaknya berkomunikasi dengan media tulisan di kertas atau layar gawai secara sabar dan jelas","Menyuruhnya pulang dan mencari pendamping keluarga","Berbicara dengan suara sangat keras berharap warga tersebut dapat mendengar","Mengabaikannya dan melayani pemohon lain yang lebih mudah diajak bicara","Memintanya menunggu berjam-jam sampai ada staf lain yang senggang"],
                'correct_answer' => 0,
                'scores' => [5,2,1,1,2],
                'explanation' => 'Inisiatif komunikasi adaptif (menulis di kertas/ponsel) menunjukkan komitmen inklusivitas pelayanan publik bagi disabilitas.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Dalam sebuah proyek lintas dinas, tim Anda ditunjuk berkolaborasi dengan unit kerja lain yang memiliki kultur kerja berbeda. Sikap Anda adalah...',
                'options' => ["Membuka ruang diskusi untuk menyamakan visi, target kerja, serta membagi peran secara adil dan transparan","Menuntut unit kerja lain mengikuti sepenuhnya kultur dan cara kerja unit Anda","Mengerjakan bagian tugas sendiri saja tanpa perlu berkoordinasi dengan anggota tim lain","Menolak bekerja sama karena merasa unit kerja Anda lebih berkompeten","Menunggu pimpinan turun tangan mengatur setiap langkah teknis"],
                'correct_answer' => 0,
                'scores' => [5,3,2,1,2],
                'explanation' => 'Kolaborasi efektif menuntut keterbukaan, koordinasi setara, serta pembagian tugas yang jelas demi tujuan bersama.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Rekan kerja satu tim Anda mengalami musibah sakit sehingga pekerjaannya terbengkalai, padahal tenggat waktu pelaporan instansi tinggal dua hari lagi. Sikap Anda...',
                'options' => ["Berkoordinasi dengan rekan lain untuk membagi tugas rekan yang sakit agar laporan selesai tepat waktu","Membiarkan laporan tersebut tidak selesai dan menyalahkan rekan yang sakit kepada atasan","Mengerjakan seluruh laporan sendiri namun meminta bayaran insentif khusus","Mengabaikan tenggat waktu karena menganggap atasan pasti memaklumi musibah","Mendesak rekan yang sedang sakit tetap masuk kantor menyelesaikan pekerjaannya"],
                'correct_answer' => 0,
                'scores' => [5,1,3,2,1],
                'explanation' => 'Solidaritas tim dan inisiatif gotong royong memecahkan beban kerja darurat mencerminkan jejaring kerja yang kokoh.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Pimpinan menunjuk Anda memimpin tim kerja yang anggotanya terdiri dari staf senior yang usianya jauh di atas Anda. Sikap Anda dalam memimpin adalah...',
                'options' => ["Menghormati senioritas mereka, mendengarkan saran bijak mereka, namun tetap tegas mengambil keputusan berdasarkan data dan musyawarah","Merasa canggung dan membiarkan para senior mengatur jalannya proyek sesuka hati","Bersikap otoriter dan menunjukkan wewenang surat keputusan pimpinan","Menolak penunjukan pimpinan karena takut berkonflik dengan senior","Hanya melibatkan rekan-rekan staf yang sebaya saja dalam pengambilan keputusan"],
                'correct_answer' => 0,
                'scores' => [5,2,2,1,2],
                'explanation' => 'Kepemimpinan adaptif memadukan rasa hormat kepada senior dengan profesionalisme manajerial berbasis musyawarah.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Dalam rapat penyusunan program kerja, rekan tim Anda mengkritik tajam proposal kegiatan yang telah Anda susun berhari-hari. Sikap Anda adalah...',
                'options' => ["Mendengarkan substansi kritiknya dengan tenang, meminta klarifikasi argumen, dan menyempurnakan proposal jika kritiknya valid","Merasa tersinggung dan menyerang balik kelemahan program kerja rekan tersebut","Langsung meninggalkan ruang rapat karena merasa kerja keras Anda tidak dihargai","Menolak merevisi proposal apa pun alasannya","Mendiamkan rekan tersebut dan menolak berbicara dengannya di luar rapat"],
                'correct_answer' => 0,
                'scores' => [5,2,1,2,1],
                'explanation' => 'Sikap terbuka terhadap masukan dan kritik konstruktif merupakan syarat mutlak kolaborasi tim berkinerja tinggi.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Unit kerja Anda bermitra dengan pihak swasta dalam program digitalisasi arsip. Anda melihat adanya potensi perbedaan persepsi terkait jadwal kerja. Yang Anda lakukan...',
                'options' => ["Mengadakan rapat sinkronisasi berkala dan menyepakati timeline kerja terperinci secara tertulis bersama mitra","Membiarkan mitra bekerja sesuai ritme mereka tanpa pengawasan","Memaksa mitra bekerja 24 jam penuh tanpa henti","Membatalkan kerja sama secara sepihak jika mitra terlambat satu hari","Menyerahkan seluruh kendali proyek kepada staf magang"],
                'correct_answer' => 0,
                'scores' => [5,2,2,1,1],
                'explanation' => 'Membangun jejaring eksternal membutuhkan komunikasi berkala, kesepakatan tertulis yang transparan, dan monitoring terukur.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Ketika tim kerja Anda meraih penghargaan atas keberhasilan inovasi program daerah, salah satu rekan Anda mengklaim bahwa kesuksesan tersebut adalah hasil kerja individunya semata. Sikap Anda...',
                'options' => ["Tetap tenang dan dalam sambutan resmi menegaskan bahwa keberhasilan ini adalah buah keringat kerja keras seluruh anggota tim","Membuat keributan dan bertengkar di depan media saat penyerahan piala","Mengunggah status bernada menyindir di media sosial pribadi","Menarik diri dari tim dan menolak bekerja sama lagi di masa depan","Mengabaikan dan membiarkan rekan tersebut mendapat seluruh bonus"],
                'correct_answer' => 0,
                'scores' => [5,1,2,2,2],
                'explanation' => 'Menjaga marwah kebersamaan tim secara elegan di forum resmi lebih bermartabat dibanding pertikaian emosional.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda mendapati informasi penting dari dinas lain yang sangat berguna untuk mempercepat proyek unit kerja Anda. Sikap Anda adalah...',
                'options' => ["Membagikan informasi tersebut kepada tim dan mengonfirmasi keabsahannya sebelum diterapkan dalam proyek","Menyimpan informasi tersebut untuk diri sendiri agar dinilai paling pintar oleh atasan","Menjual informasi tersebut kepada pihak luar yang berkepentingan","Menghapus informasi tersebut karena bukan berasal dari arahan atasan langsung","Menyebarkan informasi tersebut ke media sosial publik tanpa izin"],
                'correct_answer' => 0,
                'scores' => [5,2,1,1,1],
                'explanation' => 'Berbagi informasi kerja yang relevan demi keberhasilan tim adalah esensi jejaring kerja positif.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda mendapatkan surat penempatan tugas di daerah terpencil yang adat istiadat dan budayanya sangat berbeda jauh dari daerah asal Anda. Sikap Anda adalah...',
                'options' => ["Menerima dengan ikhlas, berusaha beradaptasi dengan budaya lokal, dan bertekad memberikan kontribusi terbaik bagi masyarakat setempat","Mengajukan permohonan mutasi kembali ke kota asal pada hari pertama bertugas","Mengurung diri di rumah dinas dan enggan bergaul dengan penduduk desa","Memaksa masyarakat setempat mengubah adatnya agar sesuai dengan gaya hidup Anda","Mengundurkan diri dari status ASN karena merasa tidak sanggup"],
                'correct_answer' => 0,
                'scores' => [5,2,1,1,1],
                'explanation' => 'ASN sebagai perekat bangsa siap ditempatkan di seluruh pelosok NKRI dan menghormati kearifan lokal setempat.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Warga di sekitar kantor penempatan Anda mengadakan tradisi syukuran adat bersama. Sebagai orang baru, sikap Anda adalah...',
                'options' => ["Menghadiri acara tersebut dengan antusias, menghormati tradisi mereka, dan berbaur ramah dengan warga","Menolak hadir dan menganggap tradisi tersebut kuno dan membuang waktu","Datang sebentar hanya untuk mengambil makanan lalu lekas pulang","Mengkritik tata cara upacara adat di depan para tetua kampung","Mengunci pintu rumah dinas pura-pura sakit"],
                'correct_answer' => 0,
                'scores' => [5,1,2,1,1],
                'explanation' => 'Menghargai tradisi kemasyarakatan lokal membangun modal sosial dan mempererat hubungan baik dengan warga binaan.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Di kantor Anda terdapat pegawai baru dari daerah lain yang belum lancar berbahasa Indonesia dan sering gugup saat rapat. Yang Anda lakukan adalah...',
                'options' => ["Mengajaknya berdiskusi santai di luar jam rapat, membantunya percaya diri, dan mendampinginya belajar istilah kerja","Menertawakan logat bicaranya bersama rekan kerja yang lain","Menyuruhnya diam saja di setiap rapat agar tidak mempermalukan tim","Meminta atasan memindahkan pegawai tersebut ke gudang arsip","Mendiamkannya dan tidak pernah mengajaknya mengobrol"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,2],
                'explanation' => 'Kepedulian dan kepekaan sosial budaya tercermin dari kesediaan mendampingi dan merangkul rekan kerja yang menghadapi kendala adaptasi.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Saat Anda merayakan hari raya keagamaan Anda, rekan kerja yang berbeda agama dengan sukarela menggantikan jadwal piket jaga kantor Anda. Tindakan balasan Anda yang tepat adalah...',
                'options' => ["Mengucapkan terima kasih tulus dan dengan senang hati bergantian menggantikannya saat rekan tersebut merayakan hari raya agamanya","Menganggap hal tersebut sudah menjadi kewajiban rekan tersebut tanpa perlu berterima kasih","Memberikan sejumlah uang tunai sebagai upah pengganti piket","Menolak bantuan tersebut karena merasa berbeda keyakinan","Meminta rekan tersebut menggantikan piket Anda di semua akhir pekan"],
                'correct_answer' => 0,
                'scores' => [5,1,2,2,1],
                'explanation' => 'Resiprositas dan solidaritas toleransi antarumat beragama memperkokoh kerukunan sosial di lingkungan kerja.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda menyaksikan perdebatan antarwarga mengenai perbedaan tata cara keagamaan yang mulai memanas di balai pertemuan. Sikap Anda...',
                'options' => ["Berusaha menenangkan situasi, mengajak kedua pihak mengutamakan persaudaraan dan toleransi, serta meredakan provokasi","Ikut memanaskan perdebatan dengan membela salah satu pihak yang seagama dengan Anda","Merekam video perdebatan dan menyebarkannya ke grup WhatsApp agar viral","Pergi meninggalkan tempat pertemuan tanpa peduli potensi kerusuhan","Mendukung warga melakukan tindakan anarkis"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,1],
                'explanation' => 'ASN berperan sebagai agen perdamaian dan peredam konflik sosial berlatar belakang SARA.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Instansi Anda mewajibkan penggunaan seragam batik bermotif kearifan lokal setiap hari Kamis, namun Anda merasa motif batik tersebut kurang sesuai dengan selera fesyen Anda. Sikap Anda...',
                'options' => ["Mematuhi aturan tersebut dan bangga mengenakan batik kearifan lokal sebagai wujud cinta budaya daerah","Membeli batik dengan motif lain sesuka hati yang lebih modern","Sengaja tidak mengenakan batik dan memakai kemeja biasa","Membuat petisi penolakan seragam batik di kantor","Mengenakan batik hanya saat ada inspeksi pimpinan saja"],
                'correct_answer' => 0,
                'scores' => [5,2,1,1,2],
                'explanation' => 'Kebanggaan pada warisan budaya daerah dan kepatuhan terhadap regulasi institusi adalah wujud cinta budaya nusantara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Di lingkungan tempat tinggal Anda terdapat tetangga yang baru pindah dari etnis minoritas dan tampak enggan berbaur karena canggung. Sikap Anda...',
                'options' => ["Menyapa dengan ramah, mengantarkan makanan ringan sebagai perkenalan, dan mengajaknya ikut kegiatan rukun tetangga","Membiarkan saja karena merasa masing-masing orang punya privasi","Mencurigai tetangga baru tersebut terlibat aksi terorisme tanpa bukti","Meminta ketua RT mengusir tetangga baru tersebut","Melarang anak-anak Anda bermain di dekat rumah tetangga tersebut"],
                'correct_answer' => 0,
                'scores' => [5,3,1,1,1],
                'explanation' => 'Inisiatif ramah dan inklusif meruntuhkan sekat kecanggungan antaretnis dalam kehidupan bermasyarakat.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Instansi Anda meluncurkan aplikasi administrasi persuratan digital berbasis cloud untuk menggantikan sistem manual. Sebagian pegawai senior merasa kesulitan mengoperasikannya. Sikap Anda adalah...',
                'options' => ["Menguasai aplikasi tersebut secara mendalam dan dengan sabar membimbing rekan-rekan senior hingga mereka mahir","Membiarkan para senior dan mengerjakan urusan Anda sendiri di sistem baru","Menyindir para senior sebagai generasi gagap teknologi yang tertinggal","Mengusulkan kepada pimpinan agar kantor kembali menggunakan kertas manual saja","Mengerjakan semua pekerjaan para senior agar Anda mendapat pujian pimpinan"],
                'correct_answer' => 0,
                'scores' => [5,3,1,2,2],
                'explanation' => 'Peer-tutoring (membimbing rekan kerja) mempercepat adopsi teknologi birokrasi dan meningkatkan produktivitas instansi.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda menerima pesan WhatsApp yang menyertakan tautan mencurigakan mengatasnamakan pembaruan data kepegawaian ASN. Tindakan Anda adalah...',
                'options' => ["Tidak mengklik tautan tersebut, memeriksa kebenaran informasi ke bagian BKD/Kepegawaian resmi, dan memperingatkan rekan kantor lain","Langsung mengklik tautan dan memasukkan data pribadi serta password","Meneruskan pesan tersebut ke semua grup kantor tanpa mengecek kebenarannya","Mengabaikan pesan dan tidak peduli jika rekan lain menjadi korban penipuan","Menyimpan pesan tersebut untuk digunakan menjahili teman kantor"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,1],
                'explanation' => 'Literasi keamanan siber dan kewaspadaan terhadap upaya phishing melindungi integritas data kepegawaian negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Dalam rangka efisiensi pelayanan publik di daerah terpencil, Anda memiliki ide membuat bot layanan informasi otomatis via WhatsApp. Langkah Anda adalah...',
                'options' => ["Menyusun konsep teknis dan proposal manfaat inovasi tersebut, lalu mempresentasikannya kepada atasan untuk mendapat persetujuan","Langsung meluncurkan bot atas nama kantor tanpa izin pimpinan","Menyimpan ide tersebut untuk kepentingan pribadi saja","Mengeluh bahwa kantor tidak menyediakan anggaran canggih","Menjual ide tersebut ke instansi lain secara ilegal"],
                'correct_answer' => 0,
                'scores' => [5,2,2,1,1],
                'explanation' => 'Inovasi teknologi yang dibarengi kepatuhan prosedur hierarki birokrasi menunjukkan kematangan kompetensi ASN digital.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Saat Anda sedang bertugas di loket, seorang warganet menyiarkan siaran langsung (live streaming) di media sosial dan mengarahkan kamera ke wajah Anda sambil melontarkan pertanyaan provokatif. Sikap Anda...',
                'options' => ["Tetap tenang, bersikap ramah, fokus menjawab pertanyaan seputar prosedur pelayanan secara jelas dan profesional tanpa terpancing emosi","Marah dan merampas gawai warganet tersebut dengan kekerasan","Meninggalkan loket dan bersembunyi di toilet","Membalas dengan kata-kata kasar dan menantangnya berkelahi","Menutup loket dan menolak melayani seluruh antrean warga hari itu"],
                'correct_answer' => 0,
                'scores' => [5,1,2,1,1],
                'explanation' => 'Ketenangan emosional dan integritas pelayanan di hadapan sorotan media digital menjaga citra positif korps ASN.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Pimpinan menugaskan Anda mencari data referensi riset kebijakan publik terbaru. Metode pemanfaatan teknologi yang paling efektif adalah...',
                'options' => ["Mengakses pangkalan data jurnal ilmiah terakreditasi dan laporan resmi lembaga pemerintah terkait yang kredibel","Mencari cuplikan informasi acak dari postingan akun anonim di media sosial","Menyalin mentah-mentah tugas rekan kantor dari tahun-tahun sebelumnya","Meminta kecerdasan buatan (AI) menulis laporan tanpa memverifikasi fakta dan sumbernya","Hanya mengandalkan buku terbitan puluhan tahun lalu tanpa mencari data terkini"],
                'correct_answer' => 0,
                'scores' => [5,1,2,3,2],
                'explanation' => 'Pemanfaatan TIK yang bertanggung jawab mengutamakan validitas data dan kredibilitas sumber informasi resmi.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda mendapati password komputer kerja Anda yang menyimpan basis data sensitif kependudukan diketahui oleh rekan staf lain. Yang Anda lakukan adalah...',
                'options' => ["Segera mengganti password dengan kombinasi yang kuat dan mengingatkan rekan tersebut tentang standar kerahasiaan data","Membiarkan saja karena merasa sesama rekan kantor tidak mungkin berbuat jahat","Membagikan password tersebut kepada staf magang agar pekerjaan lebih cepat selesai","Menonaktifkan pengamanan komputer agar mudah diakses semua orang","Menghapus seluruh file data agar tidak bisa dilihat siapa pun"],
                'correct_answer' => 0,
                'scores' => [5,2,1,1,1],
                'explanation' => 'Kepatuhan pada keamanan data pribadi dan kerahasiaan arsip negara merupakan kewajiban mutlak aparatur negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Kantor Anda menyelenggarakan pelatihan online (webinar) pemanfaatan kecerdasan buatan (AI) untuk mempercepat analisis laporan dinas di luar jam kerja. Sikap Anda...',
                'options' => ["Mendaftar dan mengikuti pelatihan tersebut secara sungguh-sungguh demi meningkatkan kompetensi kerja","Menolak ikut karena menganggap pelatihan di luar jam kerja membebani waktu luang","Masuk ke ruang webinar hanya untuk mengisi daftar hadir lalu mematikan layar gawai","Menganggap teknologi AI berbahaya dan menolak penggunaannya di birokrasi","Menyuruh orang lain mengikuti webinar atas nama Anda"],
                'correct_answer' => 0,
                'scores' => [5,2,1,1,1],
                'explanation' => 'Semangat belajar berkelanjutan (*continuous learning*) menghadapi disrupsi teknologi mencerminkan nilai AKHLAK Kompeten.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Atasan langsung Anda meminta Anda merekayasa laporan pertanggungjawaban keuangan (SPJ) kegiatan dinas agar anggaran sisa dapat dicairkan. Sikap Anda adalah...',
                'options' => ["Menolak perintah tersebut secara santun dan tegas dengan menjelaskan konsekuensi hukum pidana korupsi yang dapat merugikan instansi","Menuruti perintah atasan karena takut karir dan promosi Anda dipersulit","Menceritakan hal tersebut kepada rekan kantor di kantin tanpa mengambil tindakan resmi","Meminta bagian dari uang sisa anggaran tersebut sebagai uang tutup mulut","Langsung mengundurkan diri dari status ASN tanpa memberikan penjelasan"],
                'correct_answer' => 0,
                'scores' => [5,2,2,1,1],
                'explanation' => 'Integritas ASN menuntut keberanian menolak perintah atasan yang melanggar hukum dan berpotensi merugikan keuangan negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Seorang pengusaha rekanan tender proyek dinas menawarkan komisi sebesar 5% kepada Anda jika perusahaannya dimenangkan dalam evaluasi lelang. Yang Anda lakukan...',
                'options' => ["Menolak tegas tawaran tersebut dan melakukan penilaian secara obyektif murni berdasarkan dokumen kualifikasi teknis yang sah","Menerima tawaran tersebut karena menganggap hal semacam itu sudah lazim di proyek pemerintah","Menegosiasikan agar persentase komisi dinaikkan menjadi 10%","Menerima uangnya namun tetap menggugurkan perusahaan rekanan tersebut","Menginformasikan tawaran tersebut kepada vendor pesaing agar terjadi lelang uang suap"],
                'correct_answer' => 0,
                'scores' => [5,1,1,1,1],
                'explanation' => 'Anti-suap dan objektivitas pengadaan barang/jasa negara menjaga keadilan iklim usaha dan mencegah korupsi sistemik.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda sedang memiliki masalah pribadi keluarga yang cukup berat di rumah, namun saat tiba di kantor antrean warga pemohon pelayanan sudah menunggu Anda. Sikap Anda...',
                'options' => ["Mengesampingkan persoalan pribadi, menarik napas dalam, dan tetap melayani warga dengan senyum dan dedikasi penuh","Melayani warga dengan wajah cemberut dan marah-marah saat ditanya berkas","Mengambil izin pulang cepat dan menelantarkan antrean warga","Curhat mengenai masalah keluarga kepada warga yang sedang Anda layani","Mengunci pintu loket dan menangis di dalam ruangan"],
                'correct_answer' => 0,
                'scores' => [5,1,2,1,1],
                'explanation' => 'Profesionalisme sejati mampu memisahkan urusan personal dari tanggung jawab pelayanan publik kenegaraan.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Pimpinan memberikan tenggat waktu yang sangat ketat untuk menyelesaikan dokumen analisis kebijakan strategis kementerian. Sikap Anda adalah...',
                'options' => ["Menyusun skala prioritas, fokus bekerja penuh konsentrasi, dan jika perlu menambah jam kerja lembur agar target rampung tepat waktu","Menyerah sejak awal dan mengatakan kepada pimpinan bahwa target tersebut mustahil dipenuhi","Menyalin laporan milik kementerian lain tanpa membaca isinya demi mengejar waktu","Mengeluh kepada rekan kantor lain bahwa pimpinan terlalu menekan bawahan","Mengerjakan secara asal-asalan yang penting ada berkas yang diserahkan"],
                'correct_answer' => 0,
                'scores' => [5,2,1,2,1],
                'explanation' => 'Komitmen kerja prima dan orientasi hasil dalam situasi bertekanan tinggi mencerminkan etos kerja ASN tangguh.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda menemukan adanya celah sistem (bug) pada aplikasi keuangan kantor yang memungkinkan penarikan dana tanpa terdeteksi log audit. Tindakan Anda adalah...',
                'options' => ["Segera mendokumentasikan celah tersebut dan melaporkannya kepada pimpinan serta tim teknis pengembang agar segera ditambal","Memanfaatkan celah tersebut untuk memperkaya diri sendiri sedikit demi sedikit","Membagikan informasi celah tersebut kepada teman dekat agar ikut menikmati dana","Mendiamkan saja karena menganggap itu bukan tanggung jawab bagian kerja Anda","Mengancam pimpinan akan membocorkan celah tersebut jika tidak diberi promosi jabatan"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,1],
                'explanation' => 'Kejujuran dan kepedulian terhadap keamanan aset keuangan negara adalah cerminan nilai Akuntabel dalam Ber-AKHLAK.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Dalam penilaian Sasaran Kinerja Pegawai (SKP), seorang rekan kerja yang jarang masuk kantor meminta Anda memanipulasi absensi kehadirannya. Sikap Anda...',
                'options' => ["Menolak permintaan tersebut dengan sopan dan menyarankan rekan tersebut memperbaiki kedisiplinan kerjanya","Membantu memanipulasi absensi atas dasar rasa kasihan dan pertemanan","Meminta uang imbalan jasa manipulasi absensi","Melaporkan rekan tersebut ke pihak kepolisian dengan tuduhan makar","Membantu sekali saja dengan syarat tidak mengulanginya lagi"],
                'correct_answer' => 0,
                'scores' => [5,1,1,1,2],
                'explanation' => 'Disiplin dan integritas pelaporan kehadiran adalah fondasi akuntabilitas kinerja setiap aparatur sipil negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Instansi Anda menggelar program Jumat Bersih membersihkan lingkungan kantor, namun beberapa pegawai memilih duduk bersantai di kantin. Sikap Anda...',
                'options' => ["Tetap antusias bergotong royong membersihkan area yang menjadi tanggung jawab Anda dan mengajak rekan lain ikut serta","Ikut duduk bersantai di kantin karena merasa atasan tidak mengawasi","Menghampiri rekan di kantin lalu memarahi mereka secara kasar","Pura-pura menyapu hanya saat pimpinan lewat di depan Anda","Langsung pulang ke rumah sebelum jam kerja berakhir"],
                'correct_answer' => 0,
                'scores' => [5,1,2,2,1],
                'explanation' => 'Integritas tidak bergantung pada ada atau tidaknya pengawasan atasan, melainkan kesadaran internal berpartisipasi aktif.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Menghadapi era perubahan organisasi yang cepat, kompetensi utama yang harus selalu Anda pelihara sebagai ASN berpredikat Adaptif adalah...',
                'options' => ["Terbuka pada pembaruan, cepat menyesuaikan diri dengan regulasi baru, dan proaktif mengasah keterampilan relevan","Menolak segala bentuk inovasi dan mempertahankan cara kerja konvensional","Menunggu perintah atasan baru mau bergerak belajar","Mengkritik setiap kebijakan baru tanpa memberikan solusi alternatif","Hanya mau mengerjakan hal-hal yang tercantum dalam uraian tugas kaku"],
                'correct_answer' => 0,
                'scores' => [5,1,2,1,1],
                'explanation' => 'Nilai Adaptif menuntut ASN terus berinovasi dan antusias dalam menggerakkan ataupun menghadapi perubahan zaman.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Di grup percakapan media sosial unit kerja Anda, seorang rekan menyebarkan konten video yang memuat ujaran kebencian terhadap kelompok agama tertentu dan mengajak menentang ideologi Pancasila. Sikap Anda...',
                'options' => ["Mengingatkan di grup dengan sopan namun tegas bahwa konten tersebut melanggar hukum dan nilai ASN, serta melaporkannya kepada pimpinan jika tidak diindahkan","Ikut menyebarkan video tersebut ke grup keluarga karena merasa videonya menarik","Mendukung narasi video tersebut dan memusuhi kelompok yang disebutkan","Mendiamkan saja karena takut dimusuhi oleh rekan kerja yang menyebarkan","Keluar dari grup kantor tanpa memberikan penjelasan apa pun"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,2],
                'explanation' => 'ASN wajib menjadi benteng ideologi Pancasila dan menolak segala bentuk konten intoleransi serta radikalisme.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Seorang rekan kerja Anda mulai menunjukkan perubahan sikap yang mencolok: menarik diri dari pergaulan kantor, menolak hormat bendera saat upacara, dan sering mencap rekan lain thaghut. Tindakan Anda adalah...',
                'options' => ["Mengajaknya berdialog secara santai dari hati ke hati, menanamkan pemahaman moderasi bernegara, dan berkonsultasi dengan atasan/bagian kepegawaian untuk pendampingan","Menghakimi dan mengucilkannya dari lingkungan kantor secara bersama-sama","Ikut terpengaruh pemikiran rekan tersebut karena penasaran","Membiarkan saja karena merasa keyakinan orang lain bukan urusan Anda","Menyebarkan kabar burung bahwa rekan tersebut adalah teroris berbahaya"],
                'correct_answer' => 0,
                'scores' => [5,2,1,2,1],
                'explanation' => 'Deteksi dini dan pendekatan dialog moderat yang humanis serta eskalasi terukur ke manajemen mampu mencegah paparan radikalisme akut.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda diajak oleh seorang tokoh untuk menghadiri pertemuan tertutup sebuah organisasi yang secara terang-terangan menolak hukum negara kesatuan Republik Indonesia. Sikap Anda adalah...',
                'options' => ["Menolak ajakan tersebut secara tegas dan tetap setia memegang teguh sumpah janji setia kepada NKRI dan Pancasila","Menerima ajakan tersebut karena penasaran ingin tahu doktrin ajarannya","Menghadiri pertemuan tersebut dan ikut menjadi donatur tetap organisasi","Mengajak rekan kantor lain untuk ikut serta dalam pertemuan tertutup tersebut","Mendukung gerakan tersebut di media sosial menggunakan akun samaran"],
                'correct_answer' => 0,
                'scores' => [5,2,1,1,1],
                'explanation' => 'Sumpah setia kepada Pancasila, UUD 1945, dan NKRI adalah komitmen mutlak yang tidak boleh dikompromikan oleh aparatur negara.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Organisasi kemasyarakatan di dekat tempat tinggal Anda menyelenggarakan program moderasi beragama dan dialog antariman pemuda. Sikap Anda...',
                'options' => ["Mendukung penuh kegiatan tersebut dan aktif berpartisipasi sebagai wujud kontribusi merawat persatuan bangsa","Menolak program tersebut karena menganggap dialog antariman dapat melunturkan keyakinan pribadi","Menghasut warga sekitar untuk membubarkan acara tersebut","Mengacuhkan kegiatan tersebut karena tidak ada hubungannya dengan pekerjaan kantor","Meminta bayaran jika diminta menjadi pembicara dalam acara tersebut"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,1],
                'explanation' => 'Partisipasi aktif dalam penguatan moderasi beragama di masyarakat mempersempit ruang gerak berkembangnya paham radikal.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Sebuah yayasan yang terindikasi berafiliasi dengan jaringan ekstremisme terlarang membuka pendaftaran donasi terbuka dengan kedok bantuan kemanusiaan. Sikap Anda sebelum berdonasi...',
                'options' => ["Melakukan verifikasi legalitas izin yayasan ke Kementerian Sosial/otoritas resmi dan memastikan penyalurannya tidak melanggar hukum","Langsung mentransfer uang dalam jumlah besar tanpa memeriksa latar belakang yayasan","Mengajak seluruh pegawai kantor berdonasi ke yayasan tersebut","Tidak peduli dana tersebut digunakan untuk aksi terorisme atau tidak","Menjadi koordinator penggalangan dana yayasan tersebut di kantor"],
                'correct_answer' => 0,
                'scores' => [5,1,1,1,1],
                'explanation' => 'Kehati-hatian menelusuri legalitas lembaga pengumpul donasi mencegah aliran pendanaan bagi kelompok teroris atau gerakan radikal.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Dalam rekrutmen pegawai honorer di kantor Anda, Anda ditunjuk sebagai salah satu pewawancara. Indikator utama untuk menyaring calon yang bebas dari paham radikal adalah...',
                'options' => ["Menilai komitmen kebangsaan, kesetiaan pada Pancasila, toleransi terhadap keberagaman, dan pandangan moderat calon pegawai","Hanya memilih calon yang berasal dari suku dan agama yang sama dengan Anda","Menanyakan calon apakah bersedia mengorbankan nyawa untuk gerakan perlawanan","Memilih calon yang aktif di organisasi kemahasiswaan berpaham ekstrem","Mengabaikan aspek ideologi dan hanya melihat tampang fisiknya saja"],
                'correct_answer' => 0,
                'scores' => [5,1,1,1,1],
                'explanation' => 'Pemeriksaan komitmen kebangsaan dan wawasan moderasi dalam rekrutmen aparatur menjamin birokrasi bebas dari infiltrasi radikalisme.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Anda menemukan sebuah buku berisikan doktrin ekstremis kekerasan tertinggal di mushola kantor Anda. Langkah pertama yang Anda ambil adalah...',
                'options' => ["Mengamankan buku tersebut dan menyerahkannya kepada petugas keamanan kantor atau pengurus masjid untuk ditelusuri pemiliknya","Membaca dan mempraktikkan isi doktrin kekerasan di kantor","Memfotokopi buku tersebut dan membagikannya ke meja seluruh pegawai","Membiarkan saja buku tersebut tergeletak dibaca jamaah lain","Membakar mushola kantor karena menganggap tempat tersebut sudah terkontaminasi"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,1],
                'explanation' => 'Tindakan cepat mengamankan materi propaganda ekstremis mencegah penyebaran pengaruh negatif di tempat ibadah umum.',
                'is_active' => true,
            ],
            [
                'category_id' => $catTKP->id,
                'sub_category' => 'Karakteristik Pribadi (TKP BKN)',
                'question' => 'Sebagai seorang ASN, komitmen tertinggi dalam menjaga keutuhan Negara Kesatuan Republik Indonesia dari ancaman perpecahan diwujudkan dengan...',
                'options' => ["Menginternalisasi nilai Pancasila, bersikap adil dalam pelayanan, dan berani menolak segala bentuk ujaran kebencian pemecah belah bangsa","Mementingkan kelompok partai politik tertentu di atas kepentingan umum","Mendukung gerakan separatis yang menuntut referendum kemerdekaan","Bersikap pasif dan acuh tak acuh terhadap nasib keutuhan bangsa","Menjadikan jabatan publik sebagai sarana menumpuk kekayaan pribadi"],
                'correct_answer' => 0,
                'scores' => [5,1,1,2,1],
                'explanation' => 'Komitmen bela negara ASN terpatri dalam kesetiaan pada Pancasila, integritas pelayanan, dan ketegasan merawat persatuan nasional.',
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            Question::create($item);
        }

        $this->command->info('✅ Berhasil mengimpor 110 soal standar nasional CPNS SKD:');
        $this->command->info('   - TWK: 30 soal (Passing Grade 65)');
        $this->command->info('   - TIU: 35 soal (Passing Grade 80)');
        $this->command->info('   - TKP: 45 soal (Passing Grade 166)');
        $this->command->info('   Total Soal Aktif: ' . Question::count() . ' butir.');
    }
}
